name: Release

on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/openjdk/jdk:25-ubuntu
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - run: ./gradlew build publishMods
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}